config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  resources :restaurants do
  #   collection do
  #     get :best
  #   end
    resources :reviews, only: [:new, :create]
   end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

CATEGORYS =  ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, presence: true
  validates :adresse, presence: true
  validates :category, presence: true, inclusion: {in:CATEGORYS}
 has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: {in:RATING}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # def chef
  #   @chef_name = @restaurant.chef_name
  # end

  # def best
  #   @restaurants = Restaurant.where(rating: 5)
  # end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :adresse, :phone_number, :category)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
     @restaurant = Restaurant.find(params[:restaurant_id])
     @review = Review.new
  end
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :name %>
          <%= f.input :adresse %>
            <%= f.input :phone_number %>
              <%= f.input :category, collection: Restaurant::CATEGORYS %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
      <% end %>

app/views/restaurants/_list.html.erb
<div id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <%= render restaurant %>
      <p>
        <%= link_to "Show this restaurant", restaurant %>
      </p>
    <% end %>
  </div>
  

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
    <p>
      <strong>Name:</strong>
      <%= restaurant.name %>
    </p>
  
    <p>
      <strong>Address:</strong>
      <%= restaurant.adresse %>
    </p>
  
    <p>
      <strong>Phone Number:</strong>
      <%= restaurant.phone_number %>
    </p>
    <p>
      <strong>Category Of Restaurant:</strong>
      <%= restaurant.category %>
    </p>
  
  </div>
  

app/views/restaurants/best.html.erb
<h1>Best 5 Stars Restaurants</h1>
<%= render "list", restaurants: @restaurants %>
<%= link_to "Back to all restaurants", restaurants_path %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <p style="color: green">
    <%= notice %>
  </p>

  <h1 style="text-align: center;">Restaurants</h1>
  <div class="container">
    <div class="card" id="restaurants">
      <div class="card-body">
        <% @restaurants.each do |restaurant| %>
        <div class="card">
          <%= render restaurant %>
            <p>
              <%= link_to "View Detail" , restaurant, class: "btn btn-success" %>
            </p></div>
            <% end %>

      </div>
    </div>
  </div><br>
  <%= link_to "New restaurant" , new_restaurant_path, class: "btn btn-primary" %>
</div>

<!-- <div class="card" style="width:400px">
  <img class="card-img-top" src="img_avatar1.png" alt="Card image">
  <div class="card-body">
    <h4 class="card-title">John Doe</h4>
    <p class="card-text">Some example text.</p>
    <a href="#" class="btn btn-primary">See Profile</a>
  </div>
</div> -->

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="card">
    <p style="color: green">
      <%= notice %>
    </p>

    <%= render @restaurant %>

      <!--  -->
      <p><strong>Reviews</strong></p><br>
      <%= link_to "Create Your Review Here!!!" , new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
        <br><br>
        <div class="card">
          <ul class="list-group">
            <% @restaurant.reviews.each do |review| %>
              <li class="list-group-item">
                <%= review.rating %>
              </li>
              <li class="list-group-item">
                <%= review.content %>
              </li>
              <%= link_to "Delete" , review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"
                }%> <br>
                <% end %>
          </ul>
        </div>
        <br>

        <div>
          <%= link_to "Edit this restaurant" , edit_restaurant_path(@restaurant), class: "btn btn-info" %> <br>
            <br>

            <%= button_to "Delete this restaurant" , @restaurant, method: :delete, class: "btn btn-danger" %>
        </div>

        <%= link_to "Back to restaurants" , restaurants_path %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :rating, collection: Review::RATING %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>